language: python

branches:
  only:
    - master

install:
   pip install -r requirements.txt
matrix:
  fast_finish: true
  include:
    - python: 2.7
      script: flake8 *.py --ignore=E402,E501 && nosetests
